[package]
name = "accent"
version = "0.1.0"
authors = ["mosm <airman515@gmail.com>"]
description = "Minimal audio reverberator"

[dependencies]
itertools = "^0.7.8"
failure = "^0.1.1"
clap = "^2.32.0"
hound = "^3.4.0"
