[package]
name = "accent"
version = "0.1.0"
authors = ["mosm <airman515@gmail.com>"]
edition = "2018"
description = "Minimal audio reverberator"

[dependencies]
anyhow = "1.0.31"
clap = "2.32.0"
hound = "3.4.0"
itertools = "0.7.8"
